spring:
  h2:
    console:
      enabled: true
      path: /h2-console


  datasource:
    url: jdbc:h2:mem:jpa-basic #In-memory ??
#    url: jdbc:h2:~/jpa-basic;AUTO_SERVER=true #server ??
#    url: jdbc:h2:tcp://localhost/~/jpa-basic
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true


